# Generated by Django 4.1.5 on 2023-01-28 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_alter_blogmodel_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'verbose_name_plural': 'All Post'},
        ),
        migrations.AlterModelOptions(
            name='catagorymodel',
            options={'verbose_name_plural': 'Catagory'},
        ),
    ]
