# Generated by Django 4.1.5 on 2023-01-28 17:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_alter_blogmodel_options_alter_catagorymodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='description',
            field=tinymce.models.HTMLField(max_length=500000),
        ),
    ]
